image: php:8.0-fpm
        
pipelines:
  default:
         - step:
            name: Node Build
            image: node:16.20.1
            caches:
                - node
            script:
                - npm install
                - npm run dev
         - step:
            name: App Build
            caches:
            - composer
            script:
            - apt-get update && apt-get install -y unzip
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install 
            - php artisan config:clear
        
          